/** @import { ValueProcessorDefinition } from '../value-processor/value-processor.js'; */

const modules = await Promise.all([
  import('./aggregation-operators.js'),
  import('./alpha-constraint.js'),
  import('./alphanum-constraint.js'),
  import('./array-operator.js'),
  import('./assert-constraint.js'),
  import('./base64-constraint.js'),
  import('./base64-decode-operator.js'),
  import('./base64-encode-operator.js'),
  import('./buffer-operator.js'),
  import('./camel-case-operator.js'),
  import('./capitalize-operator.js'),
  import('./ceil-operator.js'),
  import('./compile-operator.js'),
  import('./concat-operator.js'),
  import('./conditional-operators.js'),
  import('./constant-case-operator.js'),
  import('./date-object-operator.js'),
  import('./date-operator.js'),
  import('./defined-constraint.js'),
  import('./directory-constraint.js'),
  import('./each-operator.js'),
  import('./email-constraint.js'),
  import('./entries-operator.js'),
  import('./eq-constraint.js'),
  import('./executable-constraint.js'),
  import('./file-constraint.js'),
  import('./file-size-constraint.js'),
  import('./filter-operator.js'),
  import('./flatten-operator.js'),
  import('./floor-operator.js'),
  import('./get-operator.js'),
  import('./group-by-operator.js'),
  import('./has-prefix-constraint.js'),
  import('./has-suffix-constraint.js'),
  import('./hex-constraint.js'),
  import('./hostname-constraint.js'),
  import('./http-url-constraint.js'),
  import('./in-constraint.js'),
  import('./integer-constraint.js'),
  import('./ipv4-constraint.js'),
  import('./ipv6-constraint.js'),
  import('./is-array-constraint.js'),
  import('./is-buffer-constraint.js'),
  import('./is-date-constraint.js'),
  import('./is-number-constraint.js'),
  import('./is-object-constraint.js'),
  import('./is-string-constraint.js'),
  import('./join-operator.js'),
  import('./json-constraint.js'),
  import('./json-decode-operator.js'),
  import('./json-encode-operator.js'),
  import('./kebab-case-operator.js'),
  import('./keys-operator.js'),
  import('./length-constraint.js'),
  import('./lookup-operator.js'),
  import('./lowercase-operator.js'),
  import('./map-operator.js'),
  import('./match-operator.js'),
  import('./matches-constraint.js'),
  import('./math-operators.js'),
  import('./merge-deep-operator.js'),
  import('./merge-operator.js'),
  import('./negative-constraint.js'),
  import('./never-constraint.js'),
  import('./non-empty-constraint.js'),
  import('./not-constraint.js'),
  import('./number-operator.js'),
  import('./numeric-constraint.js'),
  import('./object-operator.js'),
  import('./omit-operator.js'),
  import('./parallel-operator.js'),
  import('./pascal-case-operator.js'),
  import('./pick-operator.js'),
  import('./pipeline-operator.js'),
  import('./port-constraint.js'),
  import('./positive-constraint.js'),
  import('./process-operator.js'),
  import('./property-operator.js'),
  import('./range-constraint.js'),
  import('./reachable-constraint.js'),
  import('./readable-constraint.js'),
  import('./reference-operator.js'),
  import('./require-constraint.js'),
  import('./reverse-operator.js'),
  import('./round-operator.js'),
  import('./sequence-processors.js'),
  import('./sort-operator.js'),
  import('./split-operator.js'),
  import('./string-extra-operators.js'),
  import('./string-operator.js'),
  import('./template-operator.js'),
  import('./title-case-operator.js'),
  import('./type-operator.js'),
  import('./trim-operator.js'),
  import('./truthy-constraint.js'),
  import('./unique-operator.js'),
  import('./uppercase-operator.js'),
  import('./url-constraint.js'),
  import('./url-decode-operator.js'),
  import('./url-encode-operator.js'),
  import('./uuid-constraint.js'),
  import('./values-operator.js'),
  import('./writable-constraint.js'),
]);

/** @type {ValueProcessorDefinition[]} */
export const BUILTIN_PROCESSORS = modules.flatMap(
  ns => Object.values(ns).filter(v => v && typeof v.keyword === 'string')
);

/**
 * Get all built-in value processor definitions
 * @returns {ValueProcessorDefinition[]}
 */
export function getBuiltinProcessors() {
  return BUILTIN_PROCESSORS;
}
